/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ventanas;

/**
 *
 * @author braul
 */
public class InterfazInicial extends javax.swing.JFrame {

    /**
     * Creates new form InterfazInicial
     */
    public InterfazInicial() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonCrearProyecto = new javax.swing.JButton();
        jButtonAgregarTarea = new javax.swing.JButton();
        jButtonEditarUsuario = new javax.swing.JButton();
        jButtonEliminarTarea = new javax.swing.JButton();
        jButtonModificarTarea = new javax.swing.JButton();
        jButtonVerTarea = new javax.swing.JButton();
        jButtonAgregarUsuario = new javax.swing.JButton();
        jButtonEliminarUsuario = new javax.swing.JButton();
        jButtonVerUsuario = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButtonCrearProyecto.setBackground(new java.awt.Color(51, 51, 51));
        jButtonCrearProyecto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/project.png"))); // NOI18N
        jButtonCrearProyecto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCrearProyectoActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonCrearProyecto, new org.netbeans.lib.awtextra.AbsoluteConstraints(1050, 50, -1, -1));

        jButtonAgregarTarea.setBackground(new java.awt.Color(51, 51, 51));
        jButtonAgregarTarea.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/agregar_tareaV2.png"))); // NOI18N
        jButtonAgregarTarea.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButtonAgregarTareaMouseExited(evt);
            }
        });
        jButtonAgregarTarea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAgregarTareaActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonAgregarTarea, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, -1, -1));

        jButtonEditarUsuario.setBackground(new java.awt.Color(51, 51, 51));
        jButtonEditarUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/editar_usuario.png"))); // NOI18N
        jButtonEditarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEditarUsuarioActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonEditarUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 170, -1, -1));

        jButtonEliminarTarea.setBackground(new java.awt.Color(51, 51, 51));
        jButtonEliminarTarea.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/eliminar_tarea.png"))); // NOI18N
        getContentPane().add(jButtonEliminarTarea, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 40, -1, -1));

        jButtonModificarTarea.setBackground(new java.awt.Color(51, 51, 51));
        jButtonModificarTarea.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/editar_tarea.png"))); // NOI18N
        jButtonModificarTarea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonModificarTareaActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonModificarTarea, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 40, -1, -1));

        jButtonVerTarea.setBackground(new java.awt.Color(51, 51, 51));
        jButtonVerTarea.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/abrir_tarea.png"))); // NOI18N
        getContentPane().add(jButtonVerTarea, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 40, -1, -1));

        jButtonAgregarUsuario.setBackground(new java.awt.Color(51, 51, 51));
        jButtonAgregarUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/pngegg.png"))); // NOI18N
        getContentPane().add(jButtonAgregarUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 170, -1, -1));

        jButtonEliminarUsuario.setBackground(new java.awt.Color(51, 51, 51));
        jButtonEliminarUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/eliminar_usuario.png"))); // NOI18N
        getContentPane().add(jButtonEliminarUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 170, -1, -1));

        jButtonVerUsuario.setBackground(new java.awt.Color(51, 51, 51));
        jButtonVerUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/ver_usuario.png"))); // NOI18N
        getContentPane().add(jButtonVerUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 170, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/fondo.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-8, -6, 1610, 1030));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonCrearProyectoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCrearProyectoActionPerformed
        // TODO add your handling code here:
        InterfazCrearProyect abrir = new InterfazCrearProyect();
        abrir.setVisible(true);
    }//GEN-LAST:event_jButtonCrearProyectoActionPerformed

    private void jButtonAgregarTareaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAgregarTareaActionPerformed
        // TODO add your handling code here:
        InterfazTarea abrir = new InterfazTarea();
        abrir.setVisible(true);
    }//GEN-LAST:event_jButtonAgregarTareaActionPerformed

    private void jButtonEditarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEditarUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonEditarUsuarioActionPerformed

    private void jButtonAgregarTareaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonAgregarTareaMouseExited
        // TODO add your handling code here:
        String texto="Agregar tarea";
        jButtonAgregarTarea.setToolTipText(texto);
    }//GEN-LAST:event_jButtonAgregarTareaMouseExited

    private void jButtonModificarTareaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonModificarTareaActionPerformed
        // TODO add your handling code here:
        InterfazModificarTarea abrir = new InterfazModificarTarea();
        abrir.setVisible(true);
        String texto="Modificar tarea";
        jButtonAgregarTarea.setToolTipText(texto);
    }//GEN-LAST:event_jButtonModificarTareaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InterfazInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InterfazInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InterfazInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InterfazInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InterfazInicial().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAgregarTarea;
    private javax.swing.JButton jButtonAgregarUsuario;
    private javax.swing.JButton jButtonCrearProyecto;
    private javax.swing.JButton jButtonEditarUsuario;
    private javax.swing.JButton jButtonEliminarTarea;
    private javax.swing.JButton jButtonEliminarUsuario;
    private javax.swing.JButton jButtonModificarTarea;
    private javax.swing.JButton jButtonVerTarea;
    private javax.swing.JButton jButtonVerUsuario;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
